from enum import StrEnum


class JobState(StrEnum):
    QUEUED = "queued"; DISCOVERING = "discovering"; AWAITING_SELECTION = "awaiting_selection"
    RUNNING = "running"; PAUSED = "paused"; WAITING_AUTH = "waiting_auth"; WAITING_RETRY = "waiting_retry"
    WAITING_USER = "waiting_user"; COMPLETED = "completed"; COMPLETED_WITH_ERRORS = "completed_with_errors"
    FAILED = "failed"; CANCELLED = "cancelled"


class ItemState(StrEnum):
    DISCOVERED = "discovered"; QUEUED = "queued"; RESOLVING = "resolving"; DOWNLOADING = "downloading"
    CONVERTING = "converting"; VERIFYING = "verifying"; WAITING_AUTH = "waiting_auth"; WAITING_RETRY = "waiting_retry"
    PAUSED = "paused"; SUCCEEDED = "succeeded"; FAILED = "failed"; SKIPPED = "skipped"; CANCELLED = "cancelled"


class ErrorCode(StrEnum):
    AUTH_REQUIRED = "AUTH_REQUIRED"; ACCESS_DENIED = "ACCESS_DENIED"; FORBIDDEN = "FORBIDDEN"
    MEDIA_URL_EXPIRED = "MEDIA_URL_EXPIRED"; RATE_LIMITED = "RATE_LIMITED"; TRANSIENT_NETWORK = "TRANSIENT_NETWORK"
    INVALID_SOURCE = "INVALID_SOURCE"; UNSUPPORTED_URL = "UNSUPPORTED_URL"; UNAVAILABLE = "UNAVAILABLE"
    INTERACTION_REQUIRED = "INTERACTION_REQUIRED"; REGION_RESTRICTED = "REGION_RESTRICTED"; DRM_UNSUPPORTED = "DRM_UNSUPPORTED"
    DEPENDENCY_MISSING = "DEPENDENCY_MISSING"; DISK_FULL = "DISK_FULL"; OUTPUT_PERMISSION_DENIED = "OUTPUT_PERMISSION_DENIED"
    CONVERSION_FAILED = "CONVERSION_FAILED"; WORKER_INTERRUPTED = "WORKER_INTERRUPTED"; LIMIT_EXCEEDED = "LIMIT_EXCEEDED"

